baseURL: https://spica.starry.blue
title: spica.starry.blue
languageCode: ja-jp
theme: hello-friend-ng

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
  highlight:
    lineNos: true
    style: native

paginate: 10
rssLimit: 10
copyright: >-
  <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>

# googleAnalytics: UA-169204355-1
disqusShortname: spica-starry-blue

sitemap:
  changefreq: weekly
  priority: 0.8

hasCJKLanguage: true
imaging:
  exif:
    disableLatLong: true
defaultContentLanguage: ja

related:
  includeNewer: true
  toLower: true

enableGitInfo: true
enableEmoji: true

permalinks:
  posts: /posts/:year/:month/:filename/

author:
  name: <a href="/about">Asteria Nocturna</a> a.k.a. Nep @SlashNephy

taxonomies:
  tag: tags
  category: categories
  series: series

params:
  dateform: Jan 2, 2006
  dateformShort: Jan 2
  dateformNum: 2006-01-02
  dateformNumTime: 2006-01-02 15:04

  description: Portfolio of Nep @SlashNephy a.k.a. Asteria Nocturna
  homeSubtitle: My Portfolio

  gitUrl: https://github.com/SlashNephy/spica.starry.blue/commit/
  disableReadOtherPosts: false

    # enableThemeToggle: true
    # enableSharingButtons: true
  justifyContent: true

  social:
    - name: email
      url: mailto:spica@starry.blue
    - name: github
      url: https://github.com/SlashNephy
    - name: twitter
      url: https://twitter.com/SlashNephy
    - name: steam
      url: https://steamcommunity.com/id/AsteriaNocturna
    - name: spotify
      url: https://open.spotify.com/user/v1h824j8sxke430y505vk0wu8
    - name: amazon
      url: https://www.amazon.co.jp/registry/wishlist/3SHZC6ICOXGPT

  footer:
    enable: true

  logo:
    logoMark: '>'
    logoText: spica starry blue
    logoHomeLink: /

  portrait:
    path: https://github.com/SlashNephy.png
    alt: '@SlashNephy'

menu:
  main:
    - identifier: about
      name: About
      url: about
    - identifier: Gadgets
      name: Gadgets
      url: gadgets
    - identifier: showcase
      name: Showcase
      url: showcase
    - identifier: blog
      name: Blog
      url: https://blog.starry.blue
    - identifier: posts
      name: Posts
      url: posts
