baseURL: https://spica.starry.blue
title: spica.starry.blue
languageCode: ja-jp
theme: hello-friend-ng

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
  highlight:
    lineNos: true
    anchorLineNos: true
    codeFences: false
    style: monokai

minify:
  minifyOutput: true
  tdewolff:
    css:
      keepCSS2: true
    html:
      keepComments: false
      keepConditionalComments: false
      keepDefaultAttrVals: false
      keepDocumentTags: false
      keepEndTags: false
      keepQuotes: false
      keepWhitespace: false
    js:
      keepVarNames: false
    json:
      keepNumbers: false
    xml:
      keepWhitespace: false

paginate: 10
rssLimit: 10
copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="external license noopener" target="_blank">CC BY-SA 4.0</a>

# googleAnalytics: UA-169204355-1
disqusShortname: spica-starry-blue

sitemap:
  changefreq: weekly
  priority: 0.8

hasCJKLanguage: true
imaging:
  exif:
    disableLatLong: true
defaultContentLanguage: ja

related:
  includeNewer: true
  toLower: true

enableGitInfo: true
enableEmoji: true

permalinks:
  posts: /posts/:year/:month/:filename/

author:
  name: <a href="/about">Asteria Nocturna</a> a.k.a. Nep @SlashNephy

taxonomies:
  tag: tags
  category: categories
  series: series

params:
  dateform: Jan 2, 2006
  dateformShort: Jan 2
  dateformNum: 2006-01-02
  dateformNumTime: 2006-01-02 15:04

  description: Portfolio of Nep @SlashNephy a.k.a. Asteria Nocturna
  homeSubtitle: My Portfolio

  gitUrl: https://github.com/SlashNephy/spica.starry.blue/commit/
  disableReadOtherPosts: false

  enableThemeToggle: true
  enableSharingButtons: true
  justifyContent: true

  social:
    - name: email
      url: mailto:spica@starry.blue
    - name: github
      url: https://github.com/SlashNephy
    - name: docker
      url: https://hub.docker.com/u/slashnephy
    - name: twitter
      url: https://twitter.com/SlashNephy
    - name: discord
      url: https://discordapp.com/users/187577389419724800
    - name: reddit
      url: https://www.reddit.com/user/SlashNephy
    - name: keybase
      url: https://keybase.io/slashnephy
    - name: spotify
      url: https://open.spotify.com/user/v1h824j8sxke430y505vk0wu8
    - name: lastfm
      url: https://www.last.fm/ja/user/AsteriaNocturna
    - name: steam
      url: https://steamcommunity.com/id/AsteriaNocturna
    - name: twitch
      url: https://www.twitch.tv/asterianocturna
    - name: amazon
      url: https://www.amazon.co.jp/registry/wishlist/3SHZC6ICOXGPT

  footer:
    enable: true

  logo:
    logoMark: ">"
    logoText: spica starry blue
    logoHomeLink: /

  portrait:
    path: https://avatars.githubusercontent.com/u/7302150?v=4&s=100
    alt: "@SlashNephy"
    width: 100px
    height: 100px

menu:
  main:
    - identifier: about
      name: About
      url: about
    - identifier: Gadgets
      name: Gadgets
      url: gadgets
    - identifier: showcase
      name: Showcase
      url: showcase
    - identifier: scrapbox
      name: Scrapbox
      url: https://scrapbox.io/slashnephy/
